// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkKcmd6aJ2TdP6nuLpPjl7iXIQNYSAngY',
    appId: '1:102208827441:web:3d51ec2d0a0dbc9b32a510',
    messagingSenderId: '102208827441',
    projectId: 'todoapp-2c9ae',
    authDomain: 'todoapp-2c9ae.firebaseapp.com',
    storageBucket: 'todoapp-2c9ae.appspot.com',
    measurementId: 'G-YT6B2DRK4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgVbiE6QRh0S1WAsch3y3A1XnP_iHXmpI',
    appId: '1:102208827441:android:fda6e941cf8f9dd832a510',
    messagingSenderId: '102208827441',
    projectId: 'todoapp-2c9ae',
    storageBucket: 'todoapp-2c9ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDphROOayUxNLiXc1wvcydgLZ5YN8gybJk',
    appId: '1:102208827441:ios:24bf75454470646532a510',
    messagingSenderId: '102208827441',
    projectId: 'todoapp-2c9ae',
    storageBucket: 'todoapp-2c9ae.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDphROOayUxNLiXc1wvcydgLZ5YN8gybJk',
    appId: '1:102208827441:ios:a0467625fc35453332a510',
    messagingSenderId: '102208827441',
    projectId: 'todoapp-2c9ae',
    storageBucket: 'todoapp-2c9ae.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseApp.RunnerTests',
  );
}
